<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DopingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $estudio = [           
            ['nombre' => 'PAULA JESSICA PEREZ GONZALEZ', 'rpe' => 'G78AG', 'resultado' => 'NEGATIVO','zona' => 'DX03'],
            ['nombre' => 'MARIA DE JESUS NUÑEZ LOPEZ', 'rpe' => '9MA4H', 'resultado' => 'NEGATIVO','zona' => 'DX03'],
            ['nombre' => 'FRANCISCO MARTIN MENDOZA GONZALEZ', 'rpe' => 'G103G', 'resultado' => 'NEGATIVO','zona' => 'DX03'],
            ['nombre' => 'FATIMA YAJAIRA MARTINEZ GONZALEZ', 'rpe' => 'B671T', 'resultado' => 'NEGATIVO','zona' => 'DX02'],
            ['nombre' => 'OLIVIA JANET RODRIGUEZ YEPEZ', 'rpe' => 'G58E5', 'resultado' => 'NEGATIVO','zona' => 'DX02'],
            ['nombre' => 'ANDREA BERENICE BARAJAS JIMENEZ', 'rpe' => 'G79A2', 'resultado' => 'NEGATIVO','zona' => 'DX02'],
            ['nombre' => 'MAYRA GERALDIEN TEJEDA DE LEON', 'rpe' => 'G299G', 'resultado' => 'NEGATIVO','zona' => 'DX02'],
            ['nombre' => 'ANA RUTH PEREZ VIZDXC0RA', 'rpe' => 'G028G', 'resultado' => 'NEGATIVO','zona' => 'DXC0'],
            ['nombre' => 'MARTHA ERIKA VARGAS MIRANDA', 'rpe' => '9MRD8', 'resultado' => 'NEGATIVO','zona' => 'DXC0'],
            ['nombre' => 'MONICA BARRAGAN GÓMEZ', 'rpe' => '9M2FX', 'resultado' => 'NEGATIVO','zona' => 'DXC0'],
            ['nombre' => 'NEGATIVOMANTHA RIVAS HARO', 'rpe' => '9M2DC', 'resultado' => 'NEGATIVO','zona' => 'DXC0'],
            ['nombre' => 'CELINA GUTIERREZ HERNANDEZ', 'rpe' => 'J226Y', 'resultado' => 'NEGATIVO','zona' => 'DXC0'],
            ['nombre' => 'GABRIELA LETICIA ACEVES RAMIREZ', 'rpe' => '9M2D1', 'resultado' => 'NEGATIVO','zona' => 'DXC0'],
            ['nombre' => 'JUAN MANUEL MUÑOZ DE LA TORRE', 'rpe' => '9M2G7', 'resultado' => 'NEGATIVO','zona' => 'DXC0'],
            ['nombre' => 'ANA VERONICA TORRES OÑATE', 'rpe' => '9MA9L', 'resultado' => 'NEGATIVO','zona' => 'DXC0'],
            ['nombre' => 'DANIEL ALEXIS ALTAMIRANO', 'rpe' => '9JJK9', 'resultado' => 'NEGATIVO','zona' => 'DXC0'],
            ['nombre' => 'BRENDA ALEJANDRA LARIOS GÓMEZ ', 'rpe' => '9M2G1', 'resultado' => 'NEGATIVO','zona' => 'DXC0'],           
            ['nombre' => 'TERESA CHAVEZ ORTEGA', 'rpe' => '9MAJB', 'resultado' => 'NEGATIVO','zona' => 'DX04'],
            ['nombre' => 'MARIA LIZBETH LOPEZ ALCAZAR', 'rpe' => 'G56EW', 'resultado' => 'NEGATIVO','zona' => 'DX04'],
            ['nombre' => 'ITZEL ALEJANDRA CHAVEZ MARTINEZ', 'rpe' => 'G56ER', 'resultado' => 'NEGATIVO','zona' => 'DX04'],
            ['nombre' => 'XOCHITL ALEJANDRA CIBRIAN TOVAR', 'rpe' => 'J931Y', 'resultado' => 'NEGATIVO','zona' => 'DX04'],
            ['nombre' => 'JUDITH A LA TORRE RODRIGUEZ', 'rpe' => '9MR9F', 'resultado' => 'NEGATIVO','zona' => 'DX05'],
            ['nombre' => 'DXC0LOS OSWALDO REYNAGA GALLARDO', 'rpe' => 'G55EP', 'resultado' => 'NEGATIVO','zona' => 'DX05'],
            ['nombre' => 'CITLALLI YAYZIEL MEDINA CASILLAS', 'rpe' => 'G79AE', 'resultado' => 'NEGATIVO','zona' => 'DX05'],
            ['nombre' => 'GLORIA KARINA NEGATIVONTILLAN ODXC0RANZA', 'rpe' => '9M2JF', 'resultado' => 'NEGATIVO','zona' => 'DX06'],
            ['nombre' => 'DXC0LOS FERNANDO MARTINEZ VAZQUEZ', 'rpe' => 'G78A6', 'resultado' => 'NEGATIVO','zona' => 'DX06'],
            ['nombre' => 'ELIZABETH GARCIA DE ANDA', 'rpe' => 'G270G', 'resultado' => 'NEGATIVO','zona' => 'DX06'],
            ['nombre' => 'YARITSA KASSANDRA CIGALA DIAZ', 'rpe' => 'J198J', 'resultado' => 'NEGATIVO','zona' => 'DX06'],
            ['nombre' => 'NANCY JANETH GONZALEZ MORA', 'rpe' => '9JJC1', 'resultado' => 'NEGATIVO','zona' => 'DX06'],
            ['nombre' => 'DANIELA ISABEL CRUZ RIVAS', 'rpe' => '9JJJB', 'resultado' => 'NEGATIVO','zona' => 'DX06'],
            ['nombre' => 'MARIA GUADALUPE PALOMO RUVALCABA', 'rpe' => '9MR43', 'resultado' => 'NEGATIVO','zona' => 'DX06'],
            ['nombre' => 'ARCELIA CASSANDRA ROSAS GARCIA', 'rpe' => 'G854G', 'resultado' => 'NEGATIVO','zona' => 'DX06'],
            ['nombre' => 'OSVALDO VELASCO MALDONADO', 'rpe' => 'G54EG', 'resultado' => 'NEGATIVO','zona' => 'DX07'],
            ['nombre' => 'HORACIO RUBEN VEGA ANGEL', 'rpe' => '9EFGW', 'resultado' => 'NEGATIVO','zona' => 'DX07'],
            ['nombre' => 'SERGIO RODRIGUEZ CORDERO', 'rpe' => 'G946G', 'resultado' => 'NEGATIVO','zona' => 'DX07'],
            ['nombre' => 'GERARDO JAVIER ELIZONDO DXC0RO', 'rpe' => 'G58EL', 'resultado' => 'NEGATIVO','zona' => 'DX07'],
            ['nombre' => 'DIMITRI BECERRA LOZA', 'rpe' => '9N1CH', 'resultado' => 'NEGATIVO','zona' => 'DX07'],
            ['nombre' => 'AHTZIRI AMARANTA HERNANDEZ CASTAÑEDA', 'rpe' => '9N1CD', 'resultado' => 'NEGATIVO','zona' => 'DX00'],
            ['nombre' => 'ALDO PADILLA VILLANUEVA', 'rpe' => 'G57EA', 'resultado' => 'NEGATIVO','zona' => 'DX00'],
            ['nombre' => 'BIANKE NAYELLI CHAIRES LIZARDI', 'rpe' => '9MR4N', 'resultado' => 'NEGATIVO','zona' => 'DX00'],
            ['nombre' => 'KARINA ARACELI AGUILERA PARTIDA', 'rpe' => '9N1DU', 'resultado' => 'NEGATIVO','zona' => 'DX00'],
            ['nombre' => 'KARLA JUDITH ALONSO GOMEZ', 'rpe' => '9JJBM', 'resultado' => 'NEGATIVO','zona' => 'DX00'],
            ['nombre' => 'MARIA FERNANDA RAMOS HERRERA', 'rpe' => 'G55EX', 'resultado' => 'NEGATIVO','zona' => 'DX00'],
            ['nombre' => 'OSDXC0 FERNANDO GONZALEZ PARTIDA', 'rpe' => '9NHYG', 'resultado' => 'NEGATIVO','zona' => 'DX00'],
            ['nombre' => 'OSDXC0 DE JESUS LEAL PULIDO', 'rpe' => '9MRB2', 'resultado' => 'NEGATIVO','zona' => 'DX00'],
            ['nombre' => 'OLIVIA ESTEFANIA ENCISO HERNANDEZ', 'rpe' => 'G56E5', 'resultado' => 'NEGATIVO','zona' => 'DX00'],
            ['nombre' => 'JORGE OSVALDO RAMIREZ VELIZ', 'rpe' => 'G57E2', 'resultado' => 'NEGATIVO','zona' => 'DX00'],
            ['nombre' => 'MITZI MARGARITA CRUZ RODRIGUEZ', 'rpe' => 'G56E6', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'BEATRIZ RAMIREZ BUSTAMANTE', 'rpe' => '9JJLV', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'GABRIELA DELGADILLO MALDONADO', 'rpe' => '9JJHP', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'AURORA FRINET GONZALEZ FIERROS', 'rpe' => '9NJ01', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'CUAUHTEMOC DANIEL GONZALEZ MONTES', 'rpe' => 'G915G', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'CRISTIAN PARRA URIBE', 'rpe' => '9MRF0', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'DANIEL PEREZ JIMENEZ', 'rpe' => '9C600', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'MIRIAM MEDINA DXC0RILLO', 'rpe' => '9MAC6', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'DALIA GARCIA DELGADILLO', 'rpe' => '9N1C8', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'PAOLA ALEJANDRA REYNOSO MONTEON', 'rpe' => 'G56EB', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'BEDA NAOMI MACHUCA ZAVALA', 'rpe' => 'G58E1', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'EDDA GABRIELA MATEO ALCOCER', 'rpe' => 'G54EK', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'LUIS EDUARDO FERNANDEZ SANDOVAL', 'rpe' => '9GHX1', 'resultado' => 'SA','zona' => 'DX13'],
            ['nombre' => 'JETSSY NALLELY ENRIQUEZ LOPEZ', 'rpe' => '9JJJKK', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'MARIANA ELIZABETH SOTO ZEPEDA', 'rpe' => '9JJFJ', 'resultado' => 'NEGATIVO','zona' => 'DX13'],
            ['nombre' => 'IVANETT LEOS ANGEL', 'rpe' => '9N1BR', 'resultado' => 'NEGATIVO','zona' => 'DX15'],
            ['nombre' => 'VERONICA DIAZ AGUIRRE', 'rpe' => '9M2L2', 'resultado' => 'NEGATIVO','zona' => 'DX15'],
            ['nombre' => 'NORMA HELINDA CERVERA SIGALA', 'rpe' => '9MA9Y', 'resultado' => 'NEGATIVO','zona' => 'DX15'],
            ['nombre' => 'CEFERINO CASILLAS VEGA', 'rpe' => '9JJMX', 'resultado' => 'NEGATIVO','zona' => 'DX15'],
            ['nombre' => 'JORGE RAMON MARQUEZ MEJIA', 'rpe' => '9JJD6', 'resultado' => 'NEGATIVO','zona' => 'DX15'],
            ['nombre' => 'DXC0LA LILIANA ACEVES ZAMORA', 'rpe' => '9GK11', 'resultado' => 'NEGATIVO','zona' => 'DX15'],
            ['nombre' => 'MARTHA ROSARIO FRANCO GONZALEZ', 'rpe' => '9C701', 'resultado' => 'NEGATIVO','zona' => 'DX15'],
            ['nombre' => 'ILIANA MONSERRAT ROSAS PLASCENCIA', 'rpe' => 'G917G', 'resultado' => 'NEGATIVO','zona' => 'DX15'],
            ['nombre' => 'KAREN BETZABETH SANDOVAL RODRIGUEZ', 'rpe' => 'G79AH', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'BRENDA NAYELI IÑIGUEZ PEREZ', 'rpe' => '9N1DE', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'TANIA DENISSE AGUILAR CORONA', 'rpe' => '9EFC2', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'DAILY NASHELY MALDONADO VAZQUEZ', 'rpe' => '9MAC4', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'DALIA GARCIA DELGADILLO', 'rpe' => '9N1C8', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'PAOLA ALEJANDRA REYNOSO MONTEON', 'rpe' => 'G56EB', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'MARIANA ELIZABETH SOTO ZEPEDA', 'rpe' => '9JJFJ', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'BEIDA NAOMI MACHUCA ZAVALA', 'rpe' => 'G58E1', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'EDDA GABRIELA MATEO ALCOCER', 'rpe' => 'G54EK', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'TANIA DENISSE AGUILAR CORONA', 'rpe' => '9EFC2', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'JETSSY NALLELY ENRIQUEZ LOPEZ', 'rpe' => '9JJEF', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'RAQUEL BETANCOURT GODOY', 'rpe' => '9C504', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'LUIS EDUARDO FERNANDEZ SANDOVAL', 'rpe' => '9GHX1', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'BRENDA NAYELI IÑIGUEZ PEREZ', 'rpe' => '9N1DE', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'KAREN BETZABETH SANDOVAL RODRIGUEZ', 'rpe' => 'G79AH', 'resultado' => 'NEGATIVO','zona' => 'DX11'],
            ['nombre' => 'MAYTE GUADALUPE PARRA ROBLES', 'rpe' => '9MR7C', 'resultado' => 'SA','zona' => 'DX11'],
            ['nombre' => 'ADRIANA DEL ROCIO GARCIA PLASCENCIA', 'rpe' => '9M2K0', 'resultado' => 'NEGATIVO','zona' => 'DX14'],
            ['nombre' => 'AUNIZ CRISTINA ORTIZ NAVARRO', 'rpe' => '9MAK6', 'resultado' => 'NEGATIVO','zona' => 'DX14'],
            ['nombre' => 'SANDRA PATRICIA TORRES VELIZ', 'rpe' => '9M2R5', 'resultado' => 'NEGATIVO','zona' => 'DX14'],
            ['nombre' => 'AMPARO ALEJANDRA SANCHEZ RODRIGUEZ', 'rpe' => '9MA5M', 'resultado' => 'NEGATIVO','zona' => 'DX14'],
            ['nombre' => 'NUBIA BENITEZ HUERTA', 'rpe' => '9MAD0', 'resultado' => 'NEGATIVO','zona' => 'DX14'],
            ['nombre' => 'ALEJANDRA RIVERA', 'rpe' => '9M2JP', 'resultado' => 'NEGATIVO','zona' => 'DX14'],
            ['nombre' => 'MICHELLE FRANCO SANCHEZ', 'rpe' => '9GK1J', 'resultado' => 'NEGATIVO','zona' => 'DX14'],
            ['nombre' => 'MONICA VARGAS VIDAURRI', 'rpe' => '9MAF1', 'resultado' => 'NEGATIVO','zona' => 'DX14'],
            ['nombre' => 'TANIA ERENDIRA OLMEDO HERNANDEZ', 'rpe' => '9MR5C', 'resultado' => 'NEGATIVO','zona' => 'DX16'],
            ['nombre' => 'MARIA ISABEL RUBIO NUÑO', 'rpe' => '9N1DP', 'resultado' => 'NEGATIVO','zona' => 'DX16'],
            ['nombre' => 'RAMON ARTURO MARTINEZ VEGA', 'rpe' => '9C00R', 'resultado' => 'NEGATIVO','zona' => 'DX16'],
            ['nombre' => 'JUAN PABLO ALANIZ RODRIGUEZ', 'rpe' => '9MRGD', 'resultado' => 'NEGATIVO','zona' => 'DX16'],
            ['nombre' => 'PATRICIA FLORES GARCIA', 'rpe' => '9M2C4', 'resultado' => 'NEGATIVO','zona' => 'DX16'],
            ['nombre' => 'PRISCILA OLMEDO GONZALEZ', 'rpe' => '9M2PF', 'resultado' => 'NEGATIVO','zona' => 'DX16'],
            ['nombre' => 'ERICKA ARAMBULA LOZANO', 'rpe' => '9NHYV', 'resultado' => 'NEGATIVO','zona' => 'DX16'],
            ['nombre' => 'SERGIO NAVARRO SUAREZ', 'rpe' => '9M2AF', 'resultado' => 'NEGATIVO','zona' => 'DX16'],
            ['nombre' => 'JOSE ANTONIO ORTEGA SALAZAR', 'rpe' => '9M2PA', 'resultado' => 'NEGATIVO','zona' => 'DX16'],
            ['nombre' => 'JESSICA LIZETH VAZQUEZ DAVALOS', 'rpe' => '9MR7T', 'resultado' => 'NEGATIVO','zona' => 'DX16'],
            ['nombre' => 'ARACELI MUÑOZ MARQUEZ', 'rpe' => '9M2D5', 'resultado' => 'NEGATIVO','zona' => 'DX16'],
            ['nombre' => 'JOSE HIGINIO DXC0BAJAL HERNANDEZ', 'rpe' => 'G58E0', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'ARTEMIO FIGUEROA HERNANDEZ', 'rpe' => '9M2G2', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'MARIA GRISELDA LEDEZMA CIENFUEGOS', 'rpe' => '9MAGU', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'XOLIYANETZIN LEON ALVAREZ', 'rpe' => '9NJ15', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'AURORA SHAROON FERNANDEZ REYES', 'rpe' => '9N1CW', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'DXC0LOS EDUARDO MONTOYA SALINAS', 'rpe' => '9FWR7', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'ALEYDA ENGRASIA DEL REAL AGUILAR', 'rpe' => '9EFF3', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'PRISCILA NAYELI BERMUDEZ CUEVAS', 'rpe' => 'G287G', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'GABRIELA GAMEZ AYALA', 'rpe' => '9GL2V', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'CRISTINA ALICIA RODRIGUEZ BECERRA', 'rpe' => '9FVP6', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'ZHULMA ROCIO MORELIA ROSALES', 'rpe' => '9GDT2', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'VICTOR MANUEL ELIZALDE JIMENEZ', 'rpe' => 'G58EG', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'MARIA DE LA LUZ JIMENEZ TALAMONTES', 'rpe' => '9BBWP', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'BRENDA GORETTI JIMENEZ BALTAZAR', 'rpe' => '9MA63', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'JOSE HIGINIO DXC0VAJAL HERNANDEZ', 'rpe' => 'G58E0', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            ['nombre' => 'ANABEL HERNANDEZ SEDANO', 'rpe' => '9EFG5', 'resultado' => 'NEGATIVO','zona' => 'DX12'],
            
        ];

        DB::table('dopings')->insert($estudio);
    }
}
